name: ArrayQueue Tests

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.4'
    - name: Compile
      run: javac queue/*.java tests/queue/*.java
    
    - name: Run ArrayQueueTest
      run: java -ea tests/queue/ArrayQueueTest

    - name: Run ArrayQueueToArrayTest
      run: java -ea tests/queue/ArrayQueueToArrayTest
      
