name: Linear Tests

on:
  push:
    paths:
      - 'clojure/linear.clj'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.4'

      - name: Run LinearNaryTest
        run: |
          cd clojure
          ./TestClojure.sh cljtest.linear.LinearNaryTest

      - name: Run LinearShapelessTest
        run: |
          cd clojure
          ./TestClojure.sh cljtest.linear.LinearShapelessTest
