name: Queue Tests

on:
  push:
    paths:
    - 'java/queue/Queue.java'
    - 'java/queue/AbstractQueue.java'
    - 'java/queue/ArrayQueue.java'
    - 'java/queue/LinkedQueue.java'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.4'

    - name: Compile
      run: |
        cd java
        javac -d __out base/*.java queue/*.java

    - name: Run QueueTest
      run: |
        cd java
        java -ea -cp __out queue.QueueTest

    - name: Run QueueToArrayTest
      run: |
        cd java
        java -ea -cp __out queue.QueueToArrayTest
